const productos = [
  //abrigos
  {
    id: 1,
    titulo: "Campera Negra",
    Imagen: "./assets/img/abrigos/01.webp",
    tipo: "abrigo",
    cantidad: 1,
    defaultType: "todos",
    precio: 1000,
  },
  {
    id: 2,
    titulo: "Campera Gris",
    Imagen: "./assets/img/abrigos/02.webp",
    tipo: "abrigo",
    cantidad: 1,
    defaultType: "todos",
    precio: 1000,
  },
  {
    id: 3,
    titulo: "Campera Roja",
    Imagen: "./assets/img/abrigos/03.webp",
    tipo: "abrigo",
    cantidad: 1,
    defaultType: "todos",
    precio: 1000,
  },
  {
    id: 4,
    titulo: "Campera Azul",
    Imagen: "./assets/img/abrigos/04.webp",
    tipo: "abrigo",
    cantidad: 1,
    defaultType: "todos",
    precio: 1000,
  },
  //pantalones
  {
    id: 5,
    titulo: "Pantalon Kaizen",
    Imagen: "./assets/img/pantalones/01.webp",
    tipo: "pantalon",
    cantidad: 1,
    defaultType: "todos",
    precio: 1000,
  },
  {
    id: 6,
    titulo: "Pantalon Liso",
    Imagen: "./assets/img/pantalones/02.webp",
    tipo: "pantalon",
    cantidad: 1,
    defaultType: "todos",
    precio: 1000,
  },
  {
    id: 7,
    titulo: "Pantalon a Rayas",
    Imagen: "./assets/img/pantalones/03.webp",
    tipo: "pantalon",
    cantidad: 1,
    defaultType: "todos",
    precio: 1000,
  },
  {
    id: 8,
    titulo: "Pantalon Tipo Gastado",
    Imagen: "./assets/img/pantalones/04.webp",
    tipo: "pantalon",
    cantidad: 1,
    defaultType: "todos",
    precio: 1000,
  },
  //camisetas
  {
    id: 9,
    titulo: "Camiseta Blanca",
    Imagen: "./assets/img/camisetas/01.webp",
    tipo: "camiseta",
    cantidad: 1,
    defaultType: "todos",
    precio: 1000,
  },
  {
    id: 10,
    titulo: "Camiseta Color",
    Imagen: "./assets/img/camisetas/02.webp",
    tipo: "camiseta",
    cantidad: 1,
    defaultType: "todos",
    precio: 1000,
  },
  {
    id: 11,
    titulo: "Camiseta CoolWay",
    Imagen: "./assets/img/camisetas/03.webp",
    tipo: "camiseta",
    cantidad: 1,
    defaultType: "todos",
    precio: 1000,
  },
  {
    id: 12,
    titulo: "Camiseta NaugthyDog",
    Imagen: "./assets/img/camisetas/04.webp",
    tipo: "camiseta",
    cantidad: 1,
    defaultType: "todos",
    precio: 1000,
  },
];
